name: oaao
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_database: ^1.0.5
  firebase_core: ^0.2.5+1
  firebase_storage: ^1.0.4
  connectivity: ^0.3.2
  material_search: ^0.2.7
  carousel_slider: ^1.0.1
  url_launcher: ^3.0.3
  flutter_map:
  sqflite : any
  path_provider: '>=0.3.0'
  image_picker: ^0.4.10
  photo_view: ^0.0.7
  flutter_local_notifications: ^0.4.2+1
  datetime_picker_formfield: ^0.1.7
  firebase_auth: ^0.6.6
  multi_image_picker: ^2.3.1
  random_string: ^0.0.2
  flutter_swiper: ^1.1.4
  firebase_messaging: 2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/AppIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/logo.png
   - assets/images/image.jpg
   - assets/icons/noti_bell.png
   - assets/icons/noti_appointment.png
   - assets/icons/ask_chat.png
   - assets/icons/hospital.png
   - assets/icons/knowledge.png
   - assets/icons/medicine.png
   - assets/icons/record_book.png
   - assets/icons/doctor.png
   - assets/icons/care_procedure.png
   - assets/icons/emergency_procedure.png
   - assets/icons/life_style.png
   - assets/icons/doctor.png
   - assets/icons/fb.png
   - assets/icons/web.png
   #doc-Icons
   - assets/icons/doc_edu.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
